# Generated by Django 5.0.2 on 2024-02-26 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_table_status_booking_drink'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_drink',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking_drink',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.table'),
        ),
    ]
