# Generated by Django 5.0.2 on 2024-02-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_booking_drink_status_booking_drink_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_drink',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
