# Generated by Django 5.0.2 on 2024-02-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_booking_drink_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_drink',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
